services:
  - type: web
    name: data-engineer-django
    env: docker
    dockerContext: ./application
    dockerfilePath: ./application/Dockerfile
    plan: free
    region: oregon
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
